"""Regenerate everything derived from okdata.py.

  python docs/design/tools/build_all.py

1. Writes docs/design/data/{buildings,troops,research}.yaml (copy these into data/).
2. Runs the economy and combat simulations.
3. Replaces every `<!-- GEN:name -->` ... `<!-- /GEN:name -->` block in docs/design/*.md
   with the freshly generated table, so specs and data can never disagree.
"""

from __future__ import annotations

import contextlib
import io
import re
import sys
from pathlib import Path

import okdata as d
import sim_combat
import sim_economy

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def flow(v) -> str:
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k}: {flow(x)}" for k, x in v.items()) + " }" if v else "{}"
    if isinstance(v, str):
        return v if re.fullmatch(r"[A-Za-z0-9_]+", v) else '"' + v + '"'
    if v is None:
        return "null"
    if isinstance(v, float) and v == int(v):
        return str(int(v)) + ".0"
    return str(v)


def buildings_yaml() -> str:
    out = ["# GENERATED by docs/design/tools/build_all.py - do not edit by hand.",
           "# Spec: docs/design/01-city-economy.md. `levels[n]` is what it takes to REACH that level",
           "# (level 1 = construction) and the stats the building has AT that level.",
           "buildings:"]
    for bid, name, fp, count, unlock, _, _ in d.BUILDINGS:
        out += [f"  - id: {bid}", f"    name: {name}", f"    footprint: {fp}", f"    max_level: {d.MAX_LEVEL}",
                f"    max_count: {count}", f"    requires_city_hall: {unlock}", "    levels:"]
        for lv in range(1, d.MAX_LEVEL + 1):
            out.append("      - " + flow(d.building_level(bid, lv)))
    return "\n".join(out) + "\n"


def troops_yaml() -> str:
    out = ["# GENERATED by docs/design/tools/build_all.py - do not edit by hand.",
           "# Spec: docs/design/02-troops-and-training.md.", "troops:"]
    for t in d.ALL_TROOPS:
        out.append("  - " + flow(t))
    return "\n".join(out) + "\n"


def research_yaml() -> str:
    out = ["# GENERATED by docs/design/tools/build_all.py - do not edit by hand.",
           "# Spec: docs/design/03-research.md. `value` is the node's TOTAL effect at that level.", "research:"]
    for n in d.research_nodes():
        out += [f"  - id: {n['id']}", f"    name: {flow(n['name'])}", f"    tree: {n['tree']}",
                f"    effect: {n['effect']}", f"    max_level: {n['max_level']}",
                f"    requires: {flow(n['requires'])}", "    levels:"]
        for lv in n["levels"]:
            out.append("      - " + flow(lv))
    return "\n".join(out) + "\n"


def table(headers: list[str], rows: list[list], align: str | None = None) -> str:
    align = align or "r" * len(headers)
    sep = ["---:" if a == "r" else "---" for a in align]
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(sep) + "|"]
    for r in rows:
        lines.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(lines)


def cost_cells(cost: dict) -> list[str]:
    return [d.fmt_n(cost[r]) if cost[r] else "-" for r in d.RES]


STAT_LABEL = {
    "march_slots": "March slots", "march_capacity": "March capacity", "production_per_hour": "Production/h",
    "buffer_capacity": "Buffer", "protect_food": "Protect food", "protect_wood": "Protect wood",
    "protect_stone": "Protect stone", "protect_gold": "Protect gold", "train_batch": "Train batch",
    "hospital_capacity": "Capacity", "wall_durability": "Durability", "garrison_defense_pct": "Garrison def %",
    "tower_potency": "Tower potency", "intel_tier": "Intel tier", "scouts": "Scouts", "scout_speed": "Scout speed",
    "scout_range": "Scout range", "help_limit": "Help limit", "reinforcement_capacity": "Reinforce cap",
    "rally_capacity": "Rally capacity", "caravan_load": "Caravan load", "caravan_tax_pct": "Tax %",
    "daily_sculptures": "Daily sculptures", "commander_xp_pct": "Cmdr XP %",
}


def building_tables() -> str:
    parts = []
    for bid, name, *_ in d.BUILDINGS:
        stats = list(d.building_stats(bid, 1).keys())
        headers = ["Lv", "Food", "Wood", "Stone", "Gold", "Time", "Requires", "Power"] + [STAT_LABEL[s] for s in stats]
        rows = []
        for lv in range(1, d.MAX_LEVEL + 1):
            b = d.building_level(bid, lv)
            req = ", ".join(f"{k} {v}" for k, v in b["requires"].items()) or "-"
            rows.append([lv, *cost_cells(b["cost"]), d.fmt_time(b["time_s"]) if b["time_s"] else "-", req,
                         d.fmt_n(b["power"])] + [d.fmt_n(b[s]) if isinstance(b[s], int) else b[s] for s in stats])
        parts.append(f"#### `{bid}` - {name}\n\n" + table(headers, rows, "rrrrrrlr" + "r" * len(stats)))
    return "\n\n".join(parts)


def building_summary() -> str:
    rows = []
    for bid, name, fp, count, unlock, factor, mix in d.BUILDINGS:
        total_t = sum(d.building_level(bid, lv)["time_s"] for lv in range(1, 26))
        total_c = sum(sum(d.building_level(bid, lv)["cost"].values()) for lv in range(1, 26))
        rows.append([f"`{bid}`", name, f"{fp}x{fp}", count, unlock, factor, d.fmt_time(total_t), d.fmt_n(total_c)])
    return table(["id", "Name", "Footprint", "Max count", "Unlock CH", "Factor", "Total time 1-25 (one copy)",
                  "Total cost 1-25 (one copy)"], rows, "llrrrrrr")


def troop_table() -> str:
    rows = []
    for t in d.ALL_TROOPS:
        c = t["cost"]
        rows.append([f"`{t['id']}`", t["name"], t["attack"], t["defense"], t["health"], t["speed"], t["load"],
                     t["upkeep_food_per_hour"], t["power"], c["food"], c["wood"], c["stone"], c["gold"],
                     t["train_time_s"], f"{t['building']} {t['building_level']}"])
    return table(["id", "Name", "Atk", "Def", "HP", "Speed", "Load", "Upkeep/h", "Power", "Food", "Wood", "Stone",
                  "Gold", "Train s", "Needs"], rows, "llrrrrrrrrrrrrl")


def research_table(tree: str) -> str:
    rows = []
    for n in d.research_nodes():
        if n["tree"] != tree:
            continue
        lv = n["levels"]
        req = ", ".join(f"{k} {v}" for k, v in n["requires"].items()) or "-"
        per = lv[0]["value"]
        eff = f"`{n['effect']}`" + (f" {per:+g}/lv" if not n["effect"].startswith("unlock_") else "")
        rows.append([f"`{n['id']}`", n["name"], n["max_level"], eff,
                     f"{lv[0]['academy']}-{lv[-1]['academy']}" if len(lv) > 1 else lv[0]["academy"], req,
                     d.fmt_time(sum(x["time_s"] for x in lv)), d.fmt_n(sum(sum(x["cost"].values()) for x in lv))])
    return table(["id", "Name", "Levels", "Effect", "Academy lv", "Requires", "Total time", "Total cost"], rows,
                 "llrlrlrr")


def research_example() -> str:
    n = next(x for x in d.research_nodes() if x["id"] == "masonry")
    rows = [[lv["level"], lv["academy"], *cost_cells(lv["cost"]), d.fmt_time(lv["time_s"]), f"+{lv['value']:g}%",
             lv["power"]] for lv in n["levels"]]
    return table(["Lv", "Academy", "Food", "Wood", "Stone", "Gold", "Time", "Total effect", "Power"], rows)


def capture(fn, argv=()) -> str:
    buf = io.StringIO()
    old = sys.argv
    sys.argv = ["x", *argv]
    try:
        with contextlib.redirect_stdout(buf):
            fn()
    finally:
        sys.argv = old
    return buf.getvalue().rstrip()


def totals() -> str:
    nodes = d.research_nodes()
    rt = sum(l["time_s"] for n in nodes for l in n["levels"])
    rc = sum(sum(l["cost"].values()) for n in nodes for l in n["levels"])
    bt = sum(d.building_level(b[0], lv)["time_s"] * b[3] for b in d.BUILDINGS for lv in range(1, 26))
    bc = sum(sum(d.building_level(b[0], lv)["cost"].values()) * b[3] for b in d.BUILDINGS for lv in range(1, 26))
    bp = sum(d.building_level(b[0], 25)["power"] * b[3] for b in d.BUILDINGS)
    rp = sum(l["power"] for n in nodes for l in n["levels"])
    return table(["Quantity", "Value"], [
        ["City Hall 2-25 raw time", d.fmt_time(sum(d.CH_TIME[2:]))],
        ["All buildings to 25 raw builder time", d.fmt_time(bt)],
        ["All buildings to 25 total cost", d.fmt_n(bc)],
        ["All research raw time", d.fmt_time(rt)],
        ["All research total cost", d.fmt_n(rc)],
        ["Research node-levels", sum(n["max_level"] for n in nodes)],
        ["Power: all buildings at 25", d.fmt_n(bp)],
        ["Power: all research", d.fmt_n(rp)],
    ], "lr")


def main() -> None:
    DATA.mkdir(exist_ok=True)
    (DATA / "buildings.yaml").write_text(buildings_yaml(), encoding="utf-8", newline="\n")
    (DATA / "troops.yaml").write_text(troops_yaml(), encoding="utf-8", newline="\n")
    (DATA / "research.yaml").write_text(research_yaml(), encoding="utf-8", newline="\n")
    gen = {
        "building_summary": building_summary(),
        "building_tables": building_tables(),
        "troop_table": troop_table(),
        "research_economy": research_table("economy"),
        "research_military": research_table("military"),
        "research_example": research_example(),
        "pacing": capture(sim_economy.main, ["--markdown"]),
        "totals": totals(),
        "combat_example": "```text\n" + capture(sim_combat.main) + "\n```",
    }
    used = set()
    for md in sorted(ROOT.glob("*.md")):
        text = md.read_text(encoding="utf-8")

        def repl(m: re.Match) -> str:
            used.add(m.group(1))
            return f"<!-- GEN:{m.group(1)} -->\n{gen[m.group(1)]}\n<!-- /GEN:{m.group(1)} -->"

        new = re.sub(r"<!-- GEN:(\w+) -->.*?<!-- /GEN:\1 -->", repl, text, flags=re.S)
        if new != text:
            md.write_text(new, encoding="utf-8", newline="\n")
    print("generated blocks used:", ", ".join(sorted(used)) or "none")
    print("unused:", ", ".join(sorted(set(gen) - used)) or "none")


if __name__ == "__main__":
    main()
