class_name BuildingFactory
## Creates the 3D node for a building. Models are generated by
## tools/blender/build_buildings.py as res://assets/models/<kind>_t<tier>.glb,
## one per visual tier; the tier is picked from the building level. Falls back
## to lower tiers, then to a coloured box so new kinds are visible before
## their art exists.

const MODEL_DIR := "res://assets/models/"
const ATLAS_MATERIAL_PATH := "res://assets/materials/atlas.tres"
const TIER_COUNT := 5
const LEVELS_PER_TIER := 5

static var _atlas_material: Material


## Visual tier (1..TIER_COUNT) for a building level: levels 1-5 are tier 1,
## 6-10 tier 2, and so on.
static func tier_for_level(level: int) -> int:
	@warning_ignore("integer_division")
	return clampi(1 + (maxi(level, 1) - 1) / LEVELS_PER_TIER, 1, TIER_COUNT)


static func model_path(kind: String, tier: int) -> String:
	return "%s%s_t%d.glb" % [MODEL_DIR, kind, tier]


## Path of the best available model for `kind` at `level`: its own tier, else
## the nearest lower tier. Empty when the kind has no model at all.
static func resolve_model(kind: String, level: int) -> String:
	for tier in range(tier_for_level(level), 0, -1):
		var path := model_path(kind, tier)
		if ResourceLoader.exists(path):
			return path
	return ""


static func create(kind: String, footprint: int, level: int = 1) -> Node3D:
	var path := resolve_model(kind, level)
	if path != "":
		var scene: PackedScene = load(path)
		if scene:
			var node: Node3D = scene.instantiate()
			apply_atlas(node)
			return node
	return _placeholder(kind, footprint)


## The one material shared by every generated model (texture atlas multiplied
## by baked vertex colours).
static func atlas_material() -> Material:
	if _atlas_material == null:
		_atlas_material = load(ATLAS_MATERIAL_PATH)
	return _atlas_material


## Generated .glb files carry no materials; give every mesh the atlas material.
static func apply_atlas(node: Node) -> void:
	if node is MeshInstance3D:
		(node as MeshInstance3D).material_override = atlas_material()
	for child in node.get_children():
		apply_atlas(child)


static func _placeholder(kind: String, footprint: int) -> Node3D:
	var mesh := BoxMesh.new()
	var height := 0.6 * footprint
	mesh.size = Vector3(footprint * 0.85, height, footprint * 0.85)
	var material := StandardMaterial3D.new()
	material.albedo_color = Color.from_hsv(float(kind.hash() % 360) / 360.0, 0.45, 0.8)
	mesh.material = material
	var instance := MeshInstance3D.new()
	instance.mesh = mesh
	instance.position.y = height / 2.0
	var root := Node3D.new()
	root.add_child(instance)
	return root
